# Generated by Django 5.2.7 on 2025-12-30 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsnRiversPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('psnriver_description', models.TextField()),
                ('psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('deus_manus_img', models.ImageField(upload_to='images/')),
                ('psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-psnriver_publish_date'],
            },
        ),
    ]
