# Generated by Django 5.2.7 on 2025-12-31 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPsnRivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('about_psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('about_psnriver_description', models.TextField()),
                ('about_psnriver_description2', models.TextField()),
                ('about_psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('about_psnriver_img', models.ImageField(upload_to='images/')),
                ('about_psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('about_psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-about_psnriver_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEventsPsnRivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsandevents_psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_description', models.TextField()),
                ('newsandevents_psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_img', models.ImageField(upload_to='images/')),
                ('newsandevents_psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('newsandevents_psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-newsandevents_psnriver_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PsnRiversPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('psnriver_description', models.TextField()),
                ('psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('psnriver_img', models.ImageField(upload_to='images/')),
                ('psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-psnriver_publish_date'],
            },
        ),
    ]
