# Generated by Django 5.2.7 on 2025-12-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psnriverspost',
            old_name='deus_manus_img',
            new_name='psnriver_img',
        ),
    ]
