# Generated by Django 5.2.7 on 2026-01-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('technical_group', models.CharField(choices=[('Community Pharmacy', 'Community Pharmacy'), ('Hospital Pharmacy', 'Hospital Pharmacy'), ('Industrial Pharmacy', 'Industrial Pharmacy'), ('Administrative Pharmacy', 'Administrative Pharmacy'), ('Academic Pharmacy', 'Academic Pharmacy'), ('Regulatory Pharmacy', 'Regulatory Pharmacy')], max_length=50)),
                ('clearance_year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4)),
                ('proof_of_payment', models.FileField(upload_to='clearance/payments/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='clearance/supporting/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
