# Generated by Django 5.2.7 on 2026-01-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0002_clearanceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='declaration_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
