# Generated by Django 5.2.7 on 2026-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0003_clearanceapplication_declaration_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
