# Generated by Django 5.2.7 on 2025-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0003_aboutpsnrivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpsnrivers',
            name='about_psnriver_description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
