# Generated by Django 5.2.7 on 2025-12-30 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0004_aboutpsnrivers_about_psnriver_description2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndEventsPsnRivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsandevents_psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_description', models.TextField()),
                ('newsandevents_psnriver_description2', models.TextField()),
                ('newsandevents_psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('newsandevents_psnriver_img', models.ImageField(upload_to='images/')),
                ('newsandevents_psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('newsandevents_psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-newsandevents_psnriver_publish_date'],
            },
        ),
    ]
