# Generated by Django 5.2.7 on 2026-01-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0004_remove_clearanceapplication_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearanceapplication',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
