# Generated by Django 5.2.7 on 2025-12-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0005_newsandeventspsnrivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description2',
        ),
    ]
