# Generated by Django 5.2.7 on 2026-01-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapplication',
            name='technical_group',
            field=models.CharField(choices=[('Community Pharmacy', 'Association of Community Pharmacists of Nigeria (ACPN)'), ('Hospital Pharmacy', 'Association of Hospital & Administrative Pharmacists of Nigeria (AHAPN)'), ('Industrial Pharmacy', 'National Association of Industrial Pharmacists of Nigeria (NAIP)'), ('Administrative Pharmacy', 'Nigerian Association of Pharmacists in Academia (NAPA)'), ('Regulatory Pharmacy', 'Other / Non-traditional Practice')], max_length=50),
        ),
    ]
