# Generated by Django 5.2.7 on 2026-01-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0007_alter_clearanceapplication_technical_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
    ]
