# Generated by Django 5.2.7 on 2026-01-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0010_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
