# Generated by Django 5.2.7 on 2026-01-03 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0011_alter_notification_options_remove_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcominEventsPsnRivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_newsandevents_psnriver_title', models.CharField(blank=True, max_length=255, null=True)),
                ('upcoming_newsandevents_psnriver_status', models.CharField(blank=True, max_length=255, null=True)),
                ('upcoming_newsandevents_psnriver_description', models.TextField()),
                ('upcoming_newsandevents_psnriver_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('upcoming_newsandevents_psnriver_publish_date', models.DateTimeField(auto_now_add=True)),
                ('upcoming_newsandevents_psnriver_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upcoming_newsandevents_psnriver_publish_date'],
            },
        ),
    ]
