# Generated by Django 5.2.7 on 2026-01-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0012_upcomineventspsnrivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomineventspsnrivers',
            name='upcoming_newsandevents_psnriver_description',
        ),
    ]
