# Generated by Django 5.2.7 on 2026-01-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0013_remove_upcomineventspsnrivers_upcoming_newsandevents_psnriver_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomineventspsnrivers',
            name='upcoming_newsandevents_psnriver_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
