# Generated by Django 5.2.7 on 2026-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0014_upcomineventspsnrivers_upcoming_newsandevents_psnriver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceapplication',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
