# Generated by Django 5.2.7 on 2026-01-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0016_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_a',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_b',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_c',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_description_d',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_title_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_title_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_title_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceapplication',
            name='clearance_year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026')], max_length=4),
        ),
    ]
