# Generated by Django 5.2.7 on 2026-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0019_alter_clearanceapplication_technical_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapplication',
            name='technical_group',
            field=models.CharField(choices=[('Association of Community Pharmacists of Nigeria (ACPN)', 'Association of Community Pharmacists of Nigeria (ACPN)'), ('Association of Hospital & Administrative Pharmacists of Nigeria (AHAPN)', 'Association of Hospital & Administrative Pharmacists of Nigeria (AHAPN)'), ('National Association of Industrial Pharmacists of Nigeria (NAIP)', 'National Association of Industrial Pharmacists of Nigeria (NAIP)'), ('Administrative Pharmacy', 'Nigerian Association of Pharmacists in Academia (NAPA)'), ('Regulatory Pharmacy', 'Other / Non-traditional Practice')], max_length=200),
        ),
    ]
