# Generated by Django 5.2.7 on 2026-01-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0021_alter_clearanceapplication_technical_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsnRiversExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psnriver_executive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('psnriver_executive_position', models.TextField()),
                ('psnriver_executive_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('psnriver_executive_img', models.ImageField(upload_to='images/')),
                ('psnriver_executive_publish_date', models.DateTimeField(auto_now_add=True)),
                ('psnriver_executive_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-psnriver_executive_publish_date'],
            },
        ),
    ]
