# Generated by Django 5.2.7 on 2026-01-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0022_psnriversexecutive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psnriversexecutive',
            name='psnriver_executive_slug',
        ),
    ]
