# Generated by Django 5.2.7 on 2026-01-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0023_remove_psnriversexecutive_psnriver_executive_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psnriversexecutive',
            options={},
        ),
    ]
