# Generated by Django 5.2.7 on 2026-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnrivers', '0024_alter_psnriversexecutive_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpsnrivers',
            name='about_psnriver_img',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='newsandeventspsnrivers',
            name='newsandevents_psnriver_img',
            field=models.ImageField(upload_to='News_images/'),
        ),
        migrations.AlterField(
            model_name='psnriversexecutive',
            name='psnriver_executive_img',
            field=models.ImageField(upload_to='executive_images/'),
        ),
        migrations.AlterField(
            model_name='psnriverspost',
            name='psnriver_img',
            field=models.ImageField(upload_to='psnpost_images/'),
        ),
    ]
