# Generated by Django 5.2.7 on 2025-12-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_workplace',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_address',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_category',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_of_practice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_qualified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
