# Generated by Django 5.2.7 on 2026-01-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technical_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
