# Generated by Django 5.2.7 on 2026-01-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='technical_group',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
